name: publish

on:
  pull_request:
    branches:
      - 'master'

jobs:
  publish:
    uses: tinkoff-mobile-tech/workflows/.github/workflows/ios_lib.publish.yml@add_ios
    with:
      xcodeproj_path: "TinkoffID.xcodeproj"
      scheme_name: "TinkoffID-Package"
      podspec_name: "TinkoffID.podspec"
      bump_type: "patch"
